Fix variable names in utils (#253)
* Fix variable names in utils

* Enhance Netlify deployment workflow with retry logic

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -10,12 +10,24 @@ jobs:
     name: Wait for deployment on Netlify
     runs-on: ubuntu-latest
     steps:
-      - name: Waiting for Netlify Preview
-        uses: jakepartusch/wait-for-netlify-action@v1.4
-        id: wait-for-netflify-preview
-        with:
-          site_name: 'eventua11y'
-          max_timeout: 60
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Retry Netlify Deployment
+        run: |
+          retries=5
+          count=0
+          until $(curl --output /dev/null --silent --head --fail https://deploy-preview-${{ github.event.pull_request.number }}--eventua11y.netlify.app/); do
+            ((count++))
+            if [ ${count} -ge ${retries} ]; then
+              echo "Max retries reached, failing the job."
+              exit 1
+            fi
+            echo "Netlify site not ready, retrying in 60 seconds..."
+            sleep 60
+          done
+        env:
+          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
 
   tests_e2e_netlify:
     needs: tests_e2e_netlify_prepare
